spark_locals_without_parens = [
  allow_nil?: 1,
  always_atomic?: 1,
  argument: 2,
  argument: 3,
  batch_size: 1,
  before_action?: 1,
  constraints: 1,
  data_file: 1,
  default: 1,
  description: 1,
  document_id: 1,
  filter: 1,
  font_paths: 1,
  format: 1,
  ignore_system_fonts: 1,
  inputs: 1,
  limit: 1,
  load: 1,
  markup: 1,
  message: 1,
  not_found: 1,
  on: 1,
  only_when_valid?: 1,
  page: 1,
  pages: 1,
  pdf_options: 0,
  pdf_options: 1,
  pdf_standards: 1,
  prepare: 1,
  prepare: 2,
  public?: 1,
  read: 1,
  read: 2,
  render: 1,
  render: 2,
  root: 1,
  select: 1,
  sensitive?: 1,
  sort: 1,
  source: 1,
  template: 1,
  template: 2,
  transaction?: 1,
  validate: 1,
  validate: 2,
  where: 1
]

[
  import_deps: [:ash],
  plugins: [Spark.Formatter],
  inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"],
  locals_without_parens: spark_locals_without_parens,
  export: [locals_without_parens: spark_locals_without_parens]
]
