[package]
name = "typst_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "typst_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = ["nif_version_2_17"]
nif_version_2_15 = ["rustler/nif_version_2_15"]
nif_version_2_16 = ["rustler/nif_version_2_16"]
nif_version_2_17 = ["rustler/nif_version_2_17"]

[dependencies]
chrono = "0.4"
comemo = "0.5"
parking_lot = "0.12"
rustler = { version = "0.38", default-features = false, features = ["derive"] }
typst = "0.15"
typst-layout = "0.15"
typst-kit = { version = "0.15", default-features = false, features = [
    "embedded-fonts",
    "scan-fonts",
    "system-packages",
    "system-downloader",
    "vendor-openssl",
] }
typst-pdf = "0.15"
typst-html = "0.15"
typst-svg = "0.15"
typst-timing = "0.15"
typst-bundle = "0.15"
